global:
  scrape_interval: 15s  # Fréquence de récupération des métriques

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mlflow"
    static_configs:
      - targets: ["mlflow:5000"]
